### ISSUE TITLE
Find command triggers unexpected clear of addressbook

### ISSUE THREAD

**Issue by TanYikai** [CS2103AUG2017-F11-B1/main#78] opened 2017-11-03 07:20 UTC
when "find n/" is input, the addressbook clears all person

**Comment by Zzmobie** [comment] 2017-11-03 07:23
Again, this isn't true, it just displays the empty list.

**Comment by syy94** [comment] 2017-11-03 10:05
Duplicate of https://github.com/CS2103AUG2017-F11-B1/main/issues/76

**Closed by syy94** 2017-11-03 10:05 UTC
